install.packages("vctrs", repos = "https://cloud.r-project.org/")
install.packages("ggplot2", repos = "https://cloud.r-project.org/")
install.packages("gridExtra", repos = "https://cloud.r-project.org/")
packageVersion("vctrs")
packageVersion("ggplot2")
packageVersion("gridExtra")